In [30]:
import numpy as np
import plotly.graph_objects as go

MyShape = np.matrix([[0,1,-1,0],
                     [1,-1,-1,1]])

fig = go.Figure(
    go.Scatter(
        x = np.array(MyShape[0,:])[0],
        y = np.array(MyShape[1,:])[0],
        name = "original",
        mode = "lines"
    )
)
fig.update_layout(
    xaxis = dict(range=[-4,4]),
    yaxis = dict(range=[-4,4]),
    autosize=False,
    width=400,
    height=400
)
fig.show()

Scaling Transformation:

$$T = \begin{pmatrix} a & 0 \\ 0 & b \end{pmatrix}$$

In [37]:
def scale2(a,b):
  return np.matrix([[a,0],
                    [0,b]])

Scale shape: $S \cdot Myshape

In [14]:
scale2(4,5)*MyShape

matrix([[ 0,  4, -4,  0],
        [ 5, -5, -5,  5]])

In [18]:
fig = go.Figure(
    go.Scatter(
        x = np.array(MyShape[0,:])[0],
        y = np.array(MyShape[1,:])[0],
        name = "original",
        mode = "lines"
    )
)
NewShape = scale2(4,5)* MyShape
fig.add_trace(
    go.Scatter(
        x = np.array(NewShape[0,:])[0],
        y = np.array(NewShape[1,:])[0],
        name = "scaled",
        mode = "lines"
    )
)
fig.update_layout(
    xaxis = dict(range=[-6,6]),
    yaxis = dict(range=[-6,6]),
    autosize=False,
    width=400,
    height=400
)
fig.show()

Rotation matrix:
$$R = \begin{pmatrix} cos(x) & -sin(x) \\ sin(x) & cos(x) \end{pmatrix}$$

In [48]:
 theta = np.radians(30)
 c, s = np.cos(theta), np.sin(theta)
 R = np.array(((c, -s), (s, c)))
 print(R) 

[[ 0.8660254 -0.5      ]
 [ 0.5        0.8660254]]


In [49]:
R * MyShape

matrix([[-0.5      ,  1.3660254, -0.3660254, -0.5      ],
        [ 0.8660254, -0.3660254, -1.3660254,  0.8660254]])

In [51]:
fig = go.Figure(
    go.Scatter(
        x = np.array(MyShape[0,:])[0],
        y = np.array(MyShape[1,:])[0],
        name = "original",
        mode = "lines"
    )
)
NewShape1 = R * MyShape
fig.add_trace(
    go.Scatter(
        x = np.array(NewShape1[0,:])[0],
        y = np.array(NewShape1[1,:])[0],
        name = "Rotated",
        mode = "lines"
    )
)
fig.update_layout(
    xaxis = dict(range=[-6,6]),
    yaxis = dict(range=[-6,6]),
    autosize=False,
    width=400,
    height=400
)
fig.show()

Shear
$$S = \begin{pmatrix} 1 & k \\ 0 & 1 \end{pmatrix}$$

In [52]:
def shear1(k):
  return np.matrix([[1,k],
                    [0,1]])

In [53]:
shear1(5)*MyShape

matrix([[ 5, -4, -6,  5],
        [ 1, -1, -1,  1]])

In [54]:
fig = go.Figure(
    go.Scatter(
        x = np.array(MyShape[0,:])[0],
        y = np.array(MyShape[1,:])[0],
        name = "original",
        mode = "lines"
    )
)
NewShape = shear1(5)*MyShape
fig.add_trace(
    go.Scatter(
        x = np.array(NewShape[0,:])[0],
        y = np.array(NewShape[1,:])[0],
        name = "Shear",
        mode = "lines"
    )
)
fig.update_layout(
    xaxis = dict(range=[-6,6]),
    yaxis = dict(range=[-6,6]),
    autosize=False,
    width=400,
    height=400
)
fig.show()